### ISSUE TITLE
RSS not working 

### ISSUE THREAD

**Issue by curphey** [j0lv3r4/jolvera.dev#18]
Hello, noticed your RSS is not working. 

https://jolvera.dev/api/rss

Not sure if this is an operations issue or code but wanted to let you know. 
<img width="1130" alt="Screen Shot 2020-04-21 at 2 46 23 PM" src="https://user-images.githubusercontent.com/143776/79917190-e1a6ba00-83de-11ea-9e6d-fd03e258b7af.png">

**Comment by j0lv3r4** [comment]
Thanks for the heads up, @curphey !

I will check what's going on :thinking:

**Comment by curphey** [comment]
I think its a production thing as worked perfectly locally FYI
